import { onAuthStateChanged, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { addDoc, collection, deleteDoc, doc, getDocs, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { auth, db, firebaseReady, googleProvider, isAdmin } from "./firebase-service.js";
import { seedInitialMenu } from "./seed-menu.js";
import { updateMenuImages } from "./migrate-menu-images.js";

let currentItems = []; let unsubscribeMenu = null;
const loginPanel = document.getElementById("loginPanel"), adminPanel = document.getElementById("adminPanel"), loginStatus = document.getElementById("loginStatus"), adminStatus = document.getElementById("adminStatus"), form = document.getElementById("menuForm");

if (!firebaseReady || !auth || !db) {
  showStatus(loginStatus, "Firebase is not configured. Add your Web App configuration in firebase-config.js before using the admin area.", true);
  document.getElementById("googleLoginBtn").disabled = true;
} else {
  onAuthStateChanged(auth, handleAuthState);
}
document.getElementById("googleLoginBtn").addEventListener("click", loginWithGoogle);
document.getElementById("logoutBtn").addEventListener("click", () => signOut(auth));
form.addEventListener("submit", saveMenuItem);
document.getElementById("cancelEditBtn").addEventListener("click", resetForm);
document.getElementById("seedMenuBtn").addEventListener("click", importStarterMenu);
document.getElementById("updateMenuImagesBtn").addEventListener("click", migrateMenuImages);
document.getElementById("adminMenuList").addEventListener("click", handleListAction);
document.getElementById("orderStatusFilter").addEventListener("change", loadOrders);
document.getElementById("adminOrdersList").addEventListener("change", updateOrderStatus);

async function loginWithGoogle() { try { showStatus(loginStatus, "Opening Google sign-in…", false, "loading"); await signInWithPopup(auth, googleProvider); } catch (error) { showStatus(loginStatus, friendlyError(error), true); } }
async function handleAuthState(user) {
  if (!user) return showLogin();
  if (!isAdmin(user)) { await signOut(auth); return showLogin("This Google account is not approved to manage Sam Cafe’s menu.", true); }
  loginPanel.hidden = true; adminPanel.hidden = false; document.getElementById("adminName").textContent = user.displayName || user.email || "staff"; subscribeToMenu(); loadOrders();
}
function showLogin(message = "", isError = false) { if (unsubscribeMenu) { unsubscribeMenu(); unsubscribeMenu = null; } adminPanel.hidden = true; loginPanel.hidden = false; if (message) showStatus(loginStatus, message, isError); else loginStatus.hidden = true; }
function subscribeToMenu() { if (unsubscribeMenu) unsubscribeMenu(); showStatus(adminStatus, "Loading menu items…", false, "loading"); unsubscribeMenu = onSnapshot(query(collection(db, "menuItems"), orderBy("sortOrder", "asc")), snapshot => { currentItems = snapshot.docs.map(item => ({ id:item.id, ...item.data() })); renderMenuList(); adminStatus.hidden = true; }, error => showStatus(adminStatus, `Could not read menu items: ${friendlyError(error)}`, true)); }
function renderMenuList() { const list = document.getElementById("adminMenuList"), count = document.getElementById("menuCount"); count.textContent = `${currentItems.length} item${currentItems.length === 1 ? "" : "s"}`; if (!currentItems.length) { list.innerHTML = '<p class="empty-list">No menu items yet. Use “Import starter menu” once, or add your first item.</p>'; return; } list.innerHTML = currentItems.map(item => `<article class="admin-menu-item"><div><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.description || "")}</p><div class="admin-menu-meta"><span class="tag">${escapeHtml(item.category)}</span><span class="tag">RM ${Number(item.price || 0).toFixed(2)}</span><span class="tag">Order ${Number(item.sortOrder || 0)}</span>${item.featured ? '<span class="tag">Popular</span>' : ""}${item.available === false ? '<span class="tag tag--soldout">Sold Out</span>' : ""}</div></div><div class="item-actions"><button class="icon-button" type="button" data-action="edit" data-id="${item.id}">Edit</button><button class="icon-button icon-button--danger" type="button" data-action="delete" data-id="${item.id}">Delete</button></div></article>`).join(""); }
async function loadOrders(){if(!db)return;const list=document.getElementById("adminOrdersList"),filter=document.getElementById("orderStatusFilter").value;try{const snap=await getDocs(query(collection(db,"orders"),orderBy("createdAt","desc")));const rows=snap.docs.map(d=>({id:d.id,...d.data()})).filter(o=>filter==="all"||o.status===filter);list.innerHTML=rows.map(o=>{const label=o.orderCode||`Legacy Order · ${o.id.slice(-6)}`;return `<article class="admin-menu-item"><div><h3>${escapeHtml(label)} · ${escapeHtml(o.customerName)} · ${escapeHtml(o.status)}</h3><p>${(o.items||[]).map(i=>`${i.quantity}× ${escapeHtml(i.name)}`).join(", ")} · RM ${Number(o.total).toFixed(2)}</p></div><select data-order-id="${o.id}" aria-label="Order status"><option ${o.status==='pending_whatsapp'?'selected':''}>pending_whatsapp</option><option ${o.status==='confirmed'?'selected':''}>confirmed</option><option ${o.status==='preparing'?'selected':''}>preparing</option><option ${o.status==='ready'?'selected':''}>ready</option><option ${o.status==='completed'?'selected':''}>completed</option><option ${o.status==='cancelled'?'selected':''}>cancelled</option></select></article>`;}).join("")||'<p class="empty-list">No orders found.</p>';}catch(e){list.textContent=`Could not load orders: ${friendlyError(e)}`;}}
async function updateOrderStatus(e){const select=e.target.closest("select[data-order-id]");if(!select)return;try{await updateDoc(doc(db,"orders",select.dataset.orderId),{status:select.value,updatedAt:serverTimestamp()});showStatus(adminStatus,"Order status updated.");}catch(error){showStatus(adminStatus,`Could not update order: ${friendlyError(error)}`,true);}}
function handleListAction(event) { const button = event.target.closest("button[data-action]"); if (!button) return; const item = currentItems.find(entry => entry.id === button.dataset.id); if (!item) return; if (button.dataset.action === "edit") beginEdit(item); if (button.dataset.action === "delete") deleteMenuItem(item); }
function beginEdit(item) { form.dataset.editId = item.id; form.name.value = item.name || ""; form.description.value = item.description || ""; form.price.value = Number(item.price || 0).toFixed(2); form.sortOrder.value = Number(item.sortOrder || 0); form.category.value = item.category || "Coffee"; form.imageUrl.value = item.imageUrl || ""; form.available.checked = item.available !== false; form.featured.checked = Boolean(item.featured); document.getElementById("editorTitle").textContent = `Edit ${item.name}`; document.getElementById("saveItemBtn").textContent = "Save changes"; document.getElementById("cancelEditBtn").hidden = false; form.scrollIntoView({ behavior:"smooth", block:"start" }); }
function resetForm() { form.reset(); delete form.dataset.editId; form.available.checked = true; document.getElementById("editorTitle").textContent = "Add a menu item"; document.getElementById("saveItemBtn").textContent = "Save menu item"; document.getElementById("cancelEditBtn").hidden = true; }
async function saveMenuItem(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(form).entries()); const item = { name:data.name.trim(), description:data.description.trim(), price:Number(data.price), category:data.category, imageUrl:data.imageUrl.trim(), available:form.available.checked, featured:form.featured.checked, sortOrder:Number(data.sortOrder), updatedAt:serverTimestamp() }; const error = validateItem(item); if (error) return showStatus(adminStatus, error, true); const saveButton = document.getElementById("saveItemBtn"); saveButton.disabled = true; try { if (form.dataset.editId) { await updateDoc(doc(db, "menuItems", form.dataset.editId), item); showStatus(adminStatus, "Menu item updated."); } else { await addDoc(collection(db, "menuItems"), { ...item, createdAt:serverTimestamp() }); showStatus(adminStatus, "Menu item added."); } resetForm(); } catch (error) { showStatus(adminStatus, `Could not save item: ${friendlyError(error)}`, true); } finally { saveButton.disabled = false; } }
async function deleteMenuItem(item) { if (!window.confirm(`Delete “${item.name}”? This cannot be undone.`)) return; try { await deleteDoc(doc(db, "menuItems", item.id)); showStatus(adminStatus, "Menu item deleted."); } catch (error) { showStatus(adminStatus, `Could not delete item: ${friendlyError(error)}`, true); } }
async function importStarterMenu() { if (!window.confirm("Import the starter menu? This works only when menuItems is empty and cannot be run twice.")) return; const button = document.getElementById("seedMenuBtn"); button.disabled = true; try { const count = await seedInitialMenu(); showStatus(adminStatus, `${count} starter menu items imported.`); } catch (error) { showStatus(adminStatus, friendlyError(error), true); } finally { button.disabled = false; } }
async function migrateMenuImages() { if (!isAdmin(auth?.currentUser)) return showStatus(adminStatus, "Administrator access is required.", true); if (!window.confirm("Update only image URLs for exact starter-menu names? Prices, availability, featured state and display order will not change.")) return; const button = document.getElementById("updateMenuImagesBtn"); button.disabled = true; showStatus(adminStatus, "Updating local menu image paths…", false, "loading"); try { const result = await updateMenuImages(); const unmatched = result.unmatched.length ? ` No matching image: ${result.unmatched.join(", ")}.` : ""; showStatus(adminStatus, `Menu images updated: ${result.updated.length}; already current: ${result.skipped.length}.${unmatched}`, Boolean(result.unmatched.length)); } catch (error) { showStatus(adminStatus, `Could not update menu images: ${friendlyError(error)}`, true); } finally { button.disabled = false; } }
function validateItem(item) { if (!item.name || !item.description) return "Enter a name and description."; if (!Number.isFinite(item.price) || item.price < 0) return "Enter a valid price of RM 0.00 or more."; if (!Number.isInteger(item.sortOrder) || item.sortOrder < 0) return "Display order must be a whole number of 0 or more."; if (item.imageUrl && !/^assets\/[a-z0-9_./-]+\.(webp|jpg|jpeg|png)$/i.test(item.imageUrl)) { try { new URL(item.imageUrl); } catch { return "Use a complete image URL or a local assets/ image path."; } } return ""; }
function showStatus(element, message, isError = false, state = "") { element.textContent = message; element.className = `status${isError ? " is-error" : ""}${state ? ` is-${state}` : ""}`; element.hidden = false; }
function friendlyError(error) { return error?.code === "permission-denied" ? "Permission denied. Check your administrator UID and Firestore rules." : (error?.message || "Please try again."); }
function escapeHtml(value) { return String(value || "").replace(/[&<>'"]/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[char]); }
