import { onAuthStateChanged, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { collection, doc, getDocs, setDoc, deleteDoc, writeBatch, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { auth, db, firebaseReady, googleProvider } from "./firebase-service.js";

const LOCAL_KEY = "samCafeGuestCart"; let user = null, cart = [], menuResolver = () => null;
const byId = id => document.getElementById(id);
export function initCommerce(resolveMenu) { menuResolver = resolveMenu; bind(); cart = readLocal(); render(); if (firebaseReady && auth) onAuthStateChanged(auth, async current => { const wasGuest = !user && current; user = current; updateAccount(); if (current) await mergeGuestCart(); else { cart = readLocal(); render(); } }); else updateAccount(); }
export async function addToCart(id) { const item = menuResolver(id); if (!item || item.available === false) return status("This item is sold out."); const existing = cart.find(row => row.menuItemId === id); if (existing) existing.quantity = Math.min(20, existing.quantity + 1); else cart.push({ menuItemId:id, quantity:1, note:"" }); await save(); render(); status("Added to cart."); }
function bind() { byId("accountButton").onclick = () => { const menu=byId("accountMenu"); menu.hidden=!menu.hidden; byId("accountButton").setAttribute("aria-expanded", String(!menu.hidden)); }; byId("cartButton").onclick=()=>open("cart"); byId("drawerClose").onclick=close; byId("shopBackdrop").onclick=close; byId("clearCartBtn").onclick=async()=>{cart=[];await save();render();}; byId("checkoutBtn").onclick=()=>{ if(!user) return login(); if(!cart.length) return status("Your cart is empty."); open("checkout"); }; byId("orderType").onchange=e=>{ const dine=e.target.value==="dine_in"; byId("pickupField").hidden=dine; byId("tableField").hidden=!dine; }; byId("accountMenu").onclick=e=>{const a=e.target.dataset.accountAction;if(a==="login")login();if(a==="logout")signOut(auth);if(a==="cart")open("cart");if(a==="orders")open("orders");}; }
async function login(){ if(!firebaseReady) return status("Sign-in is unavailable until Firebase is ready."); try{await signInWithPopup(auth,googleProvider);}catch(e){status(e.message);} }
function updateAccount(){ const signed=Boolean(user); byId("accountButton").textContent=signed ? (user.displayName||"Account") : "Account"; document.querySelectorAll('[data-account-action="login"]').forEach(x=>x.hidden=signed); document.querySelectorAll('[data-account-action="cart"],[data-account-action="orders"],[data-account-action="logout"]').forEach(x=>x.hidden=!signed); }
function open(view){ byId("shopDrawer").classList.add("is-open");byId("shopBackdrop").classList.add("is-open");byId("shopDrawer").setAttribute("aria-hidden","false");["cart","checkout","orders"].forEach(x=>byId(`${x}View`).hidden=x!==view);byId("drawerTitle").textContent=view==="orders"?"My Orders":view==="checkout"?"Checkout":"My Cart";if(view==="orders")loadOrders(); }
function close(){byId("shopDrawer").classList.remove("is-open");byId("shopBackdrop").classList.remove("is-open");byId("shopDrawer").setAttribute("aria-hidden","true");}
function readLocal(){try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||"[]");}catch{return[];}} async function save(){if(user&&firebaseReady){const batch=writeBatch(db);const ref=collection(db,"users",user.uid,"cartItems");const existing=await getDocs(ref);existing.docs.filter(d=>!cart.some(row=>row.menuItemId===d.id)).forEach(d=>batch.delete(d.ref));cart.forEach(row=>batch.set(doc(ref,row.menuItemId),{...row,updatedAt:serverTimestamp()}));await batch.commit();}else localStorage.setItem(LOCAL_KEY,JSON.stringify(cart));}
async function mergeGuestCart(){const guest=readLocal();const snap=await getDocs(collection(db,"users",user.uid,"cartItems"));const remote=snap.docs.map(d=>d.data());cart=remote;for(const row of guest){const found=cart.find(x=>x.menuItemId===row.menuItemId);if(found)found.quantity=Math.min(20,found.quantity+row.quantity);else cart.push(row);}await save();localStorage.removeItem(LOCAL_KEY);render();}
function render(){const list=byId("cartItems");const rows=cart.map(row=>{const item=menuResolver(row.menuItemId);const price=item?.price||0;return `<div class="cart-row"><div><h3>${item?.name||"Unavailable item"}</h3><p>${item?.available===false?"Sold Out · ":""}RM ${Number(price).toFixed(2)}</p><div class="quantity-controls"><button data-cart="minus" data-id="${row.menuItemId}" aria-label="Reduce quantity">−</button><span>${row.quantity}</span><button data-cart="plus" data-id="${row.menuItemId}" aria-label="Increase quantity">+</button><button data-cart="remove" data-id="${row.menuItemId}">Remove</button></div></div><strong>RM ${(price*row.quantity).toFixed(2)}</strong></div>`;}).join("");list.innerHTML=rows||"<p class='menu-state'>Your cart is empty.</p>";list.onclick=async e=>{const a=e.target.dataset.cart;if(!a)return;const row=cart.find(x=>x.menuItemId===e.target.dataset.id);if(a==="remove")cart=cart.filter(x=>x!==row);if(a==="plus"&&row)row.quantity=Math.min(20,row.quantity+1);if(a==="minus"&&row)row.quantity>1?row.quantity--:cart=cart.filter(x=>x!==row);await save();render();};const total=cart.reduce((s,row)=>s+(Number(menuResolver(row.menuItemId)?.price||0)*row.quantity),0);byId("cartTotal").textContent=`RM ${total.toFixed(2)}`;byId("cartCount").textContent=cart.reduce((s,x)=>s+x.quantity,0);}
function status(message){const el=byId("drawerStatus");el.textContent=message;el.hidden=false;}
async function loadOrders(){const view=byId("ordersView");if(!user)return;const {query,where,orderBy}=await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js");try{const snap=await getDocs(query(collection(db,"orders"),where("userId","==",user.uid),orderBy("createdAt","desc")));view.innerHTML=snap.docs.map(d=>{const o=d.data(), label=o.orderCode||`Legacy Order · ${d.id.slice(-6)}`;return `<div class="cart-row"><div><h3>${label} · ${o.status}</h3><p>${(o.items||[]).map(x=>`${x.quantity}× ${x.name}`).join(", ")}</p></div><strong>RM ${Number(o.total).toFixed(2)}</strong></div>`;}).join("")||"<p class='menu-state'>No orders yet.</p>";}catch(e){view.textContent="Could not load orders.";}}
export function getCart(){return cart.slice();} export function getUser(){return user;} export function cartStatus(message){status(message);} export function refreshCart(){render();} export async function clearAfterOrder(){cart=[];await save();render();}
